name: Build

# Controls when the action will run. 
on: [push]

# Workflows
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15'
      - name: Resolve packages and run tests for contracts
        run: |
          yarn
          yarn build
          yarn test
        working-directory: ./blockchain
